# Wrangler configuration for KAPIN Sandbox Worker
# Wraps @cloudflare/sandbox SDK to provide REST API for sandbox operations

name = "kapin-sandbox-worker"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# Containers configuration (required for @cloudflare/sandbox)
[[containers]]
class_name = "Sandbox"
image = "./Dockerfile"
instance_type = "lite"
max_instances = 1

# Durable Objects binding
[[durable_objects.bindings]]
class_name = "Sandbox"
name = "Sandbox"

# Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Sandbox"]

# Observability
[observability]
enabled = true
